[allowlist]
paths = [
    '''dist/''',
    '''node_modules/''',
    '''.next/'''
]

# Known false positives
regexes = [
    '''previewModeSigningKey''',
    '''previewModeEncryptionKey''',
    '''encryptionKey'''
]
