import { describe, it, expect } from 'vitest';
import RootLayout from '../../app/layout';

// Mock the entire next/font/google module
(globalThis as any)['next/font/google'] = new Proxy({}, {
  get: () => () => ({
    className: 'inter-font-class',
    style: { fontFamily: 'Inter' }
  })
});

describe('RootLayout', () => {
  it('renders layout with children', () => {
    const children = <div>Test Content</div>;
    const element = <RootLayout>{children}</RootLayout>;
    
    expect(element).toBeDefined();
    expect(element.type).toBe(RootLayout);
    expect(element.props.children).toBe(children);
  });

  it('has correct metadata', () => {
    const metadata = {
      title: 'Acme Web App',
      description: 'Generated by create next app'
    };
    
    expect(metadata.title).toBe('Acme Web App');
    expect(metadata.description).toBe('Generated by create next app');
  });
});
