name: Dependabot Auto-Merge
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  dependabot:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Approve Dependabot PR
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PAT }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr review --approve "$PR_URL"

      - name: Enable auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PAT }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr merge --auto --merge "$PR_URL"